sudo: required

language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '12'

after_success:
  - npx semantic-release

branches:
  except:
    - "/\\d+\\.\\d+\\.\\d+$/"
