# Builds the package and runs all tests.
name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest

      - name: Install modules
        run: npm ci --no-audit

      - name: Lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test
